apiVersion: apps/v1
kind: Deployment
metadata:
  name: invitaion-card-ui-deployment
  labels:
    app: invitation-card 
    type: ui
spec:
  selector:
    matchLabels:
      app: invitation-card
      type: ui
  replicas: 2
  template:
    metadata:
      name: invitation-card-ui-pod
      labels:
        app: invitation-card
        type: ui
    spec:
      containers:
        - name: invitation-card-ui-container
          image: anupgeorge/invitationcard-image:latest


