apiVersion: apps/v1
kind: Deployment
metadata:
  name: invitation-card-api-deployment
  labels:
    app: invitation-card-api
    type: api
spec:
  selector:
    matchLabels:
      app: invitation-card-api
      type: back-end
  replicas: 1
  template:
    metadata:
      name: invitation-card-api-pod
      labels:
        app: invitation-card-api
        type: back-end
    spec:
      containers:
        - name: invitation-card-api-container
          image: anupgeorge/invitationcard-api-image:20230929T0312331695957153
          ports:
          - containerPort: 3000
          env:
            - name: DB_HOST
              value: "192.168.65.2"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "invitationcard"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: db_password            
            - name: TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: token_key