name: UI Deployment Trigger
# Controls when the workflow will run
on: [repository_dispatch]
jobs:
  Echoing:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Script triggered
        run: echo "Triggering Wokflow ${{ github.event.client_payload.sha }}"
        
  
